language: php

php:
  - 5.6
  - 7.0
  - 7.1
  
matrix:
  include:
    - php: 5.5
      env: COMPOSER_FLAGS=--prefer-lowest

before_script:
    # php module
    #- echo "extension = xsl.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install: composer install
script: vendor/bin/phpunit
